cli:
  name: ethsuper

log:
  level: info
  # console or json
  format: console

eth:
  network: mainnet
  # ETH execution layer connection address
  elAddr:
  # ETH consensus layer connection address
  clAddr:
  # Oracle member's private key（Make enough ETH to support the GAS of transactions; without ‘0x’ prefix）
  privateKey: